### ISSUE TITLE
getting a backtester import error

### ISSUE THREAD

**Issue by mwiser** [Auquan/Tutorials#18]
see screenshot
<img width="825" alt="screen shot 2018-03-13 at 9 19 05 pm" src="https://user-images.githubusercontent.com/26651479/37381711-3bf23bb8-2704-11e8-8d77-7b768cb99320.png">

**Comment by mwiser** [comment]
Worked around it - FYI

**Comment by TeamAuquan** [comment]
Saw that this is fixed. But mentioning it anyways: you need the auquan toolbox (pip install -U auquan_toolbox) in the same path where you are running your notebook from.

**Comment by yan365** [comment]
from backtester.dataSource.yahoo_data_source import YahooStockDataSource
from datetime import datetime
​
startDateStr = '2007/12/01'
endDateStr = '2017/12/01'
cachedFolderName = 'yahooData/'
dataSetId = 'testPairsTrading'
instrumentIds = ['SPY','AAPL','ADBE','SYMC','EBAY','MSFT','QCOM',
                 'HPQ','JNPR','AMD','IBM']
ds = YahooStockDataSource(cachedFolderName=cachedFolderName,
                            dataSetId=dataSetId,
                            instrumentIds=instrumentIds,
                            startDateStr=startDateStr,
                            endDateStr=endDateStr,
                            event='history')
data = ds.getBookDataByFeature()['Adj Close']
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-aafa708b5250> in <module>
----> 1 from backtester.dataSource.yahoo_data_source import YahooStockDataSource
      2 from datetime import datetime
      3 
      4 startDateStr = '2007/12/01'
      5 endDateStr = '2017/12/01'

ModuleNotFoundError: No module named 'backtester'

**Comment by yan365** [comment]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-aafa708b5250> in <module>
----> 1 from backtester.dataSource.yahoo_data_source import YahooStockDataSource
      2 from datetime import datetime
      3 
      4 startDateStr = '2007/12/01'
      5 endDateStr = '2017/12/01'

ModuleNotFoundError: No module named 'backtester'

**Comment by caseyyangsissi** [comment]
> Worked around it - FYI

<img width="865" alt="Screenshot 2019-06-17 at 14 36 04" src="https://user-images.githubusercontent.com/51916509/59608488-55b46980-910d-11e9-9c15-8af5444845c8.png">
import error happened again, will appreciate that if you could help

**Comment by chandinijain** [comment]
you need the auquan toolbox (pip install -U auquan_toolbox) in the same path where you are running your notebook from.

**Comment by caseyyangsissi** [comment]
I tried it , unfortunately it didn't work for some reasons....
________________________________
发件人: chandinijain <notifications@github.com>
发送时间: 2019年6月17日 14:47
收件人: Auquan/Tutorials
抄送: Yang, Kaixi; Comment
主题: Re: [Auquan/Tutorials] getting a backtester import error (#18)


you need the auquan toolbox (pip install -U auquan_toolbox) in the same path where you are running your notebook from.

―

**Comment by chandinijain** [comment]
@caseyyangsissi it seems that the toolbox might be installed in a different path compared to where you are running the notebook from. This sometimes happens if you have multiple versions of python installed. The path that the notebook is importing packages from is different from the path where the commandline is installing packages.

Please see a fix here: https://www.lucypark.kr/blog/2013/02/10/when-python-imports-and-ipython-does-not/

**Comment by ATMCH18** [comment]
use `pip3 install -U auquan_toolbox` instead of `pip install -U auquan_toolbox` 
I did have the same problem and pip3 solved it.
