### ISSUE TITLE
Chart is wrong

### ISSUE THREAD

**Issue by worthy7** [Auquan/Tutorials#24]
On the notebook "Integration, Cointegration..." The chart just above the title "Testing for cointegration" is wrong on the github preview. I think it just needs reuploading.

This is mine:
![image](https://user-images.githubusercontent.com/4762399/63663966-9f9d8800-c7ff-11e9-97c1-081e7f9243f4.png)

**Comment by davidardagh** [comment]
This has been reuploaded
