### ISSUE TITLE
pair trading backtester logic is wrong

### ISSUE THREAD

**Issue by PercyARS** [Auquan/Tutorials#29]
your PnL calculation for the exit scenario is wrong
```python
        elif abs(zscore[i]) < 0.5:
            money += countS1*S1[i] - S2[i] * countS2
            count = 0
```

not sure what you are resetting `count` for since it was never used in the code.  and why is countS2 making a negative impact to PnL? if you fix these two issues, the strategy is not profitable at all.

**Comment by chandinijain** [comment]
@PercyARS this is now fixed, thanks for pointing it out
