### ISSUE TITLE
'DataFrame' object has no attribute 'set_value'

### ISSUE THREAD

**Issue by rdpreg** [Auquan/Tutorials#40]
Hello guys, i'm trying to run the code. Can you help with this issue?!

Thanks

!['DataFrame' object has no attribute 'set_value'](https://user-images.githubusercontent.com/30996645/77849664-ab8d6600-71a3-11ea-920e-04622886c26e.png)

**Comment by trinibossman** [comment]
Was this ever answered? I'm having the same issue

**Comment by davidardagh** [comment]
Hi guys,

This error is caused by an upgrade to Pandas that removed this function. We will address this in a future update, but from now the toolbox requires you use pandas version .24.

David

**Comment by chandinijain** [comment]
you can do this by adding `!pip install pandas==0.24.2 --user` to your notebook to version lock pandas
